###
##
# FUNCTIONS AND PACKAGES
##
###


# gen_RDS_files_with_prl_raw_data() ---------------------------------------

# One RDS file for patiens and one for controls. The files contain all 
# raw PRL data, with the psychtoolkit code for each subject. The output is:
# here("data", "processed", "prl", STIMULUS, "patients_with_psychtoolkit_code.rds")
# here("data", "processed", "prl", STIMULUS, "controls_with_psychtoolkit_code.rds")

#' @description 
#' Generate four RDS files (group: 2 x condition: 2) with raw PRL data of each
#' participant.
#' @input
#' Raw data generated by psychtoolkit. 
#' @return 
#' NULL. 
#' @export
load_psychtoolkit_files <- function() {
  
  generate_rds_for_prl(CONDITION = "control_stranger", GENDER = "prl_female")
  generate_rds_for_prl(CONDITION = "control_stranger", GENDER = "prl_male")
  generate_rds_for_prl(CONDITION = "surprise_stranger", GENDER = "prl_female")
  generate_rds_for_prl(CONDITION = "surprise_stranger", GENDER = "prl_male")
}


# generate_rds_for_prl() --------------------------------------------------

#' @description 
#' generate RDS file for PRL data
#' @return NULL.
#' @param 
#' GROUP: patient, control
#' STIMULUS: food, social
generate_rds_for_prl <- function(CONDITION, GENDER) {
  
  dir <- here("data", "raw", "prl", CONDITION, GENDER, "experiment_data")
  
  file_names <- as.character(list.files(path=dir, pattern = "prl_"))
  n_files <- length(file_names)
  n_files
  
  d_list <- list()
  
  for (i in 1:n_files) {
    
    d  <- read.table(here("data", "raw", "prl", CONDITION, GENDER, "experiment_data", file_names[i]))
    
    d$subj_idx <- file_names[i]
    d$epoch <- d$V1
    d$temp1 <- d$V2
    d$is_self <- d$V3
    d$is_surprise <- d$V4
    d$trial <- d$V5
    d$momentary_happiness <- d$V6
    d$rt_happiness <- d$V7
    d$temp2 <- d$V8
    d$most_rewarded_image <- d$V9
    d$rt <- d$V10
    d$feedback <- d$V11 # 1 = reward, 2 = punishment, 3 = too slow
    d$chosen_stimulus <- d$V12
    d$video_number <- d$V13
    d$inter_trial_delay <- d$V14
    d$x_coord_orange <- d$V15
    d$x_coord_white <- d$V16
    d$cumulative_total_reward <- d$V17
    d$orange_img_number <- d$V18
    d$white_img_number <- d$V19
    d$temp3 <- d$V20
    d$temp4 <- d$V21
    d$temp5 <- d$V22
    
    d1 <- d |> 
      dplyr::select(!starts_with("temp"))
    
    d2 <- d1 |> 
      dplyr::select(!c(
        "V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V10", 
        "V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", "V20", 
        "V21", "V22")
      )
    
    d_list[[i]] <- d2
  }
  
  # convert list into data.frame
  df <- do.call(rbind.data.frame, d_list)
  
  if (CONDITION == "control_stranger" & GENDER == "prl_female") {
    saveRDS(df, here("data", "prep", "prl", "interim", "control_stranger_females.rds"))
  } else if (CONDITION == "control_stranger" & GENDER == "prl_male") {
    saveRDS(df, here("data", "prep", "prl", "interim", "control_stranger_males.rds"))
  } else if (CONDITION == "surprise_stranger" & GENDER == "prl_female") {
    saveRDS(df, here("data", "prep", "prl", "interim", "surprise_stranger_females.rds"))
  } else if (CONDITION == "surprise_stranger" & GENDER == "prl_male") {
      saveRDS(df, here("data", "prep", "prl", "interim", "surprise_stranger_males.rds"))
  } else {
    stop(0)
  }
  
}


# gen_data_list_with_prl_raw_data() ---------------------------------------

# Generate data list and add subj_name
# Reads the four RDS files with the raw PRL data, adds subj_name used in the
# questionnaires. The four data.frame are added to a list.

#' @description 
#' Read the raw data and add subj_name.
#' @input NULL
#' @return data_list list with 4 DataFrames:
#' data_list[[1]] : df_food_patients
#' data_list[[2]] : df_food_controls
#' data_list[[3]] : df_social_patients
#' data_list[[4]] : df_social_controls

write_prl_raw_data_list <- function() {
  
  df_1 <- add_quest_code_to_data(
    CONDITION = "control_stranger", 
    GENDER = "prl_female"
  )
  
  df_2 <- add_quest_code_to_data(
    CONDITION = "control_stranger", 
    GENDER = "prl_male"
  )
  
  df_3 <- add_quest_code_to_data(
    CONDITION = "surprise_stranger", 
    GENDER = "prl_female"
  )
  
  df_4 <- add_quest_code_to_data(
    CONDITION = "surprise_stranger", 
    GENDER = "prl_male"
  )
  
  data_list <- list()
  
  data_list[[1]] <- df_1
  data_list[[2]] <- df_2
  data_list[[3]] <- df_3
  data_list[[4]] <- df_4
  
  mydata <- do.call(rbind.data.frame, data_list)
  
  mydata
}



# add_quest_code_to_data() ------------------------------------------------


#' @description 
#' Generate a data.frame with the raw PRL data and the subj_name codes.
#' As input are used the psytoolkit codes.
#' @return 
#' Data.frame.
add_quest_code_to_data <- function(CONDITION, GENDER) {
  
  correspondence_table_for_subj_codes <- 
    gen_correspondence_table_codes(CONDITION, GENDER)
  
  if (CONDITION == "control_stranger" & GENDER == "prl_female") {
    data_psytoolkit_code <- readRDS(
      here("data", "prep", "prl", "interim", "control_stranger_females.rds")
    ) %>% 
      dplyr::rename("code_psytoolkit" = "subj_idx")
  } else if (CONDITION == "control_stranger" & GENDER == "prl_male") {
    data_psytoolkit_code <- readRDS(
      here("data", "prep", "prl", "interim", "control_stranger_males.rds")
    ) %>% 
      dplyr::rename("code_psytoolkit" = "subj_idx")
  } else if (CONDITION == "surprise_stranger" & GENDER == "prl_female") {
    data_psytoolkit_code <- readRDS(
      here("data", "prep", "prl", "interim", "surprise_stranger_females.rds")
    ) %>% 
      dplyr::rename("code_psytoolkit" = "subj_idx")
  } else if (CONDITION == "surprise_stranger" & GENDER == "prl_male") {
    data_psytoolkit_code <- readRDS(
      here("data", "prep", "prl", "interim", "surprise_stranger_males.rds")
    ) %>% 
      dplyr::rename("code_psytoolkit" = "subj_idx")
  }
  
  df <- left_join(
    data_psytoolkit_code, correspondence_table_for_subj_codes,  
    by = "code_psytoolkit"
  )
  df
}


# gen_correspondence_table_codes() ----------------------------------------


#' @description 
#' by using the information in the Excel file, generates a correspondence table
#' which associates the codes used by psytoolkit with the codes used in the
#' questionnaires
#' @return data.frame.
gen_correspondence_table_codes <- function(CONDITION, GENDER) {
  
  d <- read_excel_code(CONDITION, GENDER)
  d <- gen_subj_name(d)
  d$is_surprise <- CONDITION
  
  d_clean <- d %>% 
    dplyr::rename("user_id" = "subj_id") %>% 
    dplyr::select(user_id, code_psytoolkit)
  
  d_clean2 <- d_clean[!is.na(d_clean$code_psytoolkit), ] 
  # d_food_clean2$code_psytoolkit
  d_clean2
}


# read_excel_code() -------------------------------------------------------


#' @description 
#' read Excel file.
#' @return data.frame.
#' @param 
#' GROUP = "patients", EXCEL_FILE = "misc_food".
read_excel_code <- function(CONDITION, GENDER) {
  d <- readxl::read_excel(
    here("data", "raw", "prl", CONDITION, GENDER, "data.xlsx")
  )
  d
}


# gen_subj_name() ---------------------------------------------------------


#' @description 
#' generate subject code
#' @return data.frame.
#' @param data.frame.
gen_subj_name <- function(d) {
  
  library("stringi")
  
  d$mese_c <- ifelse(
    d$`mese_1` < 10, stri_join("0", as.character(d$`mese_1`), sep=''), as.character(d$`mese_1`)
  )
  
  d$giorno_c <- ifelse(
    d$`giorno_1` < 10, 
    stri_join("0", as.character(d$`giorno_1`), sep=''), 
    as.character(d$`giorno_1`)
  )
  
  d$cellulare_c <- ifelse(
    d$`cellulare_1` < 100, 
    stri_join("0", as.character(d$`cellulare_1`), sep=''), 
    as.character(d$`cellulare_1`)
  )
  
  d$sex <- ifelse(d$`sesso_1` == 1, "f",
                  ifelse(d$`sesso_1` == 2, "m", NA))
  
  d$subj_id <- tolower(
    stri_join(d$`nome_1`, d$`cognome_1`, d$`anno_1`, 
              d$mese_c, d$giorno_c, d$cellulare_c, d$sex, 
              sep='_')
  )
  
  d$code_psytoolkit <- d$`esperimento_1`
  
  d
}

